### ISSUE TITLE
scheduled.py: not a valid identifier

### ISSUE THREAD

**Issue by aame1** [vishwa35/slackbot-tutorial#2]
Hello, 

I wanted to try out this simple bot for Slack, but whenever I want to test the scheduler via the bash export command, i get this: 

"bash: export: `scheduled.py': not a valid identifier"

how i'm using it : 

export SLACK_BOT_TOKEN="xoxb-00000" python scheduled.py

I'm running it while being in the slack-tutorial, after having forked and cloned the github repository. 

OS : SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux

**Comment by jasonsalas** [comment]
Hi @aame1 - it might be because the demo is based on the existence of a channel named **#test**, it looks like that might be referring to the channel ID not being found.

You can query to see all the channels in your workspace with `curl -F token=<YOUR_TOKEN> https://slack.com/api/channels.list`

Hope this helps! :)

**Comment by vishwa35** [comment]
Hey @aame1!

Seems like your trouble was with the export command.
The freeCodeCamp version of the tutorial seems to have warped some of the text with missing newlines, etc. I've just updated the original medium post -- see the updated tutorial [here](https://medium.com/free-code-camp/how-to-build-a-basic-slackbot-a-beginners-guide-6b40507db5c5).

It seems your problem was that you were running this command as 1 line:
```> export SLACK_BOT_TOKEN="xoxb-00000" python scheduled.py```

it should be run, however, as two lines
```
> export SLACK_BOT_TOKEN="xoxb-00000" 
> python scheduled.py
```

hope this helps. sorry for the late response!
